#!/bin/bash

set -eo pipefail

main() {
    local current_directory=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
    local dir
    if [[ -n "$JAVASCRIPT_IPYTHON_DIR" ]]; then 
        dir="$JAVASCRIPT_IPYTHON_DIR"
    else
        dir="$current_directory/../notebooks"
        mkdir -p "$dir"
    fi

    if [[ -n "$JAVASCRIPT_IPYTHON_WORKING_DIR" ]]; then
        working_dir="$JAVASCRIPT_IPYTHON_WORKING_DIR"
    else
        working_dir="$dir"
    fi
    . venv/bin/activate; "$current_directory/../node_modules/.bin/ijs" --notebook-dir="$dir" --ijs-working-dir="$working_dir"
}
main
